#!/usr/bin/env python3
"""Generate agent specification markdown files."""

from pathlib import Path

OUT = Path(__file__).parent

TEMPLATE = """# {num}. {name}

| Field | Value |
|-------|-------|
| **Wave** | {wave} |
| **Priority** | {priority} |
| **Status** | `planned` |
| **LangGraph Node** | {langgraph} |
| **Primary Model** | {primary_model} |
| **Owner** | AI Platform Team |

---

## Purpose

{purpose}

## Responsibilities

{responsibilities}

## Inputs

```json
{inputs}
```

## Outputs

```json
{outputs}
```

## Tools

{tools}

## Models

| Task | Model | Fallback |
|------|-------|----------|
{models_table}

## Memory

{memory}

## Prompt (Summary)

```
{prompt}
```

## Workflows

{workflows}

## KPIs

{kpis}

## Failure Handling

{failure}

## Observability

{observability}

## Security

{security}

## Test Cases

{tests}

## Implementation Notes

{implementation}
"""


def fmt_list(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items)


def fmt_models(primary: str, fallback: str = "GPT-4o-mini") -> str:
    return f"| Primary | {primary} | {fallback} |"


def write(slug: str, **kwargs) -> None:
    path = OUT / f"{slug}.md"
    if path.exists() and slug.startswith(("0", "1", "2", "3")) and int(slug[:2]) <= 6:
        print(f"skip existing {slug}")
        return
    content = TEMPLATE.format(**kwargs)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {slug}")


AGENTS = [
    {
        "slug": "07-rag-agent",
        "num": 7,
        "name": "RAG Agent",
        "wave": 1,
        "priority": "P0",
        "langgraph": "RAG Node",
        "primary_model": "Embeddings + GPT-4o",
        "purpose": "Retrieve relevant books, courses, lessons, and knowledge assets for teaching.",
        "responsibilities": fmt_list([
            "Vector search over curriculum content",
            "Chunk ranking and re-ranking",
            "Source attribution for citations",
            "Tenant-scoped knowledge isolation",
        ]),
        "inputs": '{"query":"Explain present perfect","student_id":"uuid","top_k":5,"filters":{"course_id":"optional"}}',
        "outputs": '{"chunks":[{"text":"...","source":"Lesson 3","score":0.91}],"citations":["Course A / Unit 2"]}',
        "tools": "Qdrant, PostgreSQL metadata, embedding service",
        "models_table": fmt_models("text-embedding-3-small", "local embeddings"),
        "memory": "Qdrant (vectors), PostgreSQL (metadata)",
        "prompt": "Retrieve top-k passages relevant to the student query and level.",
        "workflows": "Context Manager → RAG Agent → Teacher Agent",
        "kpis": fmt_list(["Recall@5 > 85%", "P95 retrieval < 300ms"]),
        "failure": "Qdrant unavailable → keyword SQL fallback; empty results → general knowledge disclaimer",
        "observability": "Log query, top scores, source IDs",
        "security": "Tenant filter on all queries; no cross-org leakage",
        "tests": fmt_list([
            "Grammar query returns grammar lesson chunk",
            "Unknown topic returns empty with safe fallback",
        ]),
        "implementation": "Not implemented. Requires Qdrant collection per tenant.",
    },
    # Wave 2
    {
        "slug": "08-pronunciation-agent",
        "num": 8,
        "name": "Pronunciation Agent",
        "wave": 2,
        "priority": "P1",
        "langgraph": "Voice Analysis Node",
        "primary_model": "Whisper + phoneme engine",
        "purpose": "Analyze phoneme accuracy, stress, fluency, and intonation from student speech.",
        "responsibilities": fmt_list([
            "Transcribe audio via Whisper",
            "Phoneme alignment and scoring",
            "Stress and intonation analysis",
            "Per-word pronunciation feedback",
        ]),
        "inputs": '{"session_id":"uuid","audio_url":"s3://...","target_text":"optional","locale":"en-US"}',
        "outputs": '{"phoneme_score":82,"stress_score":78,"words":[{"word":"hello","score":0.9,"tip":"..."}]}',
        "tools": "Whisper, phoneme engine, audio preprocessor",
        "models_table": fmt_models("Whisper large-v3", "Whisper base"),
        "memory": "Redis (session audio state)",
        "prompt": "Score pronunciation against reference phonemes; give actionable micro-tips.",
        "workflows": "Audio → Whisper → Phoneme Engine → Scoring → Feedback",
        "kpis": fmt_list(["Phoneme scoring correlation > 0.8 vs human raters", "P95 pipeline < 5s"]),
        "failure": "Low audio quality → route to Speech Quality Agent; ASR fail → retry once",
        "observability": "Log audio duration, ASR confidence, score distribution",
        "security": "Encrypt audio at rest; auto-delete per retention policy",
        "tests": fmt_list(["Clear speech scores > 80", "Mispronounced 'th' flagged"]),
        "implementation": "Not implemented. Browser STT exists; server-side pipeline pending.",
    },
    {
        "slug": "09-fluency-agent",
        "num": 9,
        "name": "Fluency Agent",
        "wave": 2,
        "priority": "P1",
        "langgraph": "Voice Analysis Node",
        "primary_model": "Rules + GPT-4o-mini",
        "purpose": "Detect pauses, hesitations, speaking speed, and confidence markers.",
        "responsibilities": fmt_list([
            "Measure words per minute",
            "Detect long pauses and fillers",
            "Compute fluency index 0–100",
            "Trend fluency over sessions",
        ]),
        "inputs": '{"transcript":"...","timestamps":[],"audio_metrics":{}}',
        "outputs": '{"fluency":84,"wpm":128,"pauses":3,"fillers":2,"confidence":"medium"}',
        "tools": "Timestamp analyzer, statistical scorer",
        "models_table": fmt_models("GPT-4o-mini", "rule-based"),
        "memory": "PostgreSQL (fluency history)",
        "prompt": "Summarize fluency patterns in one encouraging sentence plus one improvement tip.",
        "workflows": "Pronunciation Agent output → Fluency Agent → Speaking report",
        "kpis": fmt_list(["Fluency score stability ±5 across re-runs", "Report generation < 1s"]),
        "failure": "Missing timestamps → estimate from transcript length",
        "observability": "Track WPM distribution by CEFR level",
        "security": "Aggregate metrics only in dashboards",
        "tests": fmt_list(["Hesitation-heavy transcript scores < 60", "Smooth speech scores > 75"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "10-grammar-agent",
        "num": 10,
        "name": "Grammar Agent",
        "wave": 2,
        "priority": "P1",
        "langgraph": "Language Analysis Node",
        "primary_model": "GPT-4o",
        "purpose": "Detect grammar, tense, articles, and sentence structure errors in speech and text.",
        "responsibilities": fmt_list([
            "Error detection and classification",
            "Correction with explanation",
            "Pattern tracking per student",
            "Severity scoring",
        ]),
        "inputs": '{"text":"I goed to school yesterday","student_id":"uuid","mode":"speech|writing"}',
        "outputs": '{"errors":[{"type":"verb_tense","original":"goed","correction":"went","rule":"..."}],"score":72}',
        "tools": "LanguageTool (optional), LLM grammar checker",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "Memory Agent (mistake patterns)",
        "prompt": "Identify grammar errors; explain briefly; suggest one practice exercise.",
        "workflows": "Conversation → Grammar Agent → inline correction",
        "kpis": fmt_list(["Precision > 90% on labeled set", "False positive rate < 5%"]),
        "failure": "Ambiguous sentence → ask clarifying question instead of correcting",
        "observability": "Error type histogram per tenant",
        "security": "No storage of offensive content beyond moderation pipeline",
        "tests": fmt_list(["Article omission detected", "Correct sentence returns zero errors"]),
        "implementation": "Partial: `grammar` agent stub in AGENT_REGISTRY.",
    },
    {
        "slug": "11-vocabulary-agent",
        "num": 11,
        "name": "Vocabulary Agent",
        "wave": 2,
        "priority": "P1",
        "langgraph": "Language Analysis Node",
        "primary_model": "GPT-4o-mini",
        "purpose": "Analyze vocabulary range, word repetition, and lexical complexity.",
        "responsibilities": fmt_list([
            "Unique word count and diversity",
            "Repetition and overuse detection",
            "CEFR level estimation",
            "Suggest richer alternatives",
        ]),
        "inputs": '{"text":"...","student_id":"uuid","target_level":"B1"}',
        "outputs": '{"unique_words":42,"repetitions":["good"],"cefr_estimate":"B1","suggestions":["excellent","wonderful"]}',
        "tools": "Lexical database, n-gram analyzer",
        "models_table": fmt_models("GPT-4o-mini", "frequency lists"),
        "memory": "Memory Agent (vocabulary gaps)",
        "prompt": "Highlight 2–3 words to upgrade; keep tone supportive.",
        "workflows": "Writing/speaking analysis → Vocabulary Agent → report",
        "kpis": fmt_list(["CEFR estimate within ±1 level", "Suggestion relevance > 80%"]),
        "failure": "Very short input → skip complexity analysis",
        "observability": "Track vocabulary growth over time",
        "security": "Student text not used for model training",
        "tests": fmt_list(["Repeated 'nice' flagged", "Advanced essay rated B2+"]),
        "implementation": "Partial: `vocabulary` agent stub in AGENT_REGISTRY.",
    },
    {
        "slug": "12-accent-agent",
        "num": 12,
        "name": "Accent Agent",
        "wave": 2,
        "priority": "P2",
        "langgraph": "Voice Analysis Node",
        "primary_model": "Acoustic classifier + GPT-4o-mini",
        "purpose": "Assess accent quality, regional influence, and recommend targeted practice.",
        "responsibilities": fmt_list([
            "Accent classification",
            "Intelligibility scoring",
            "Regional pattern identification",
            "Practice drill recommendations",
        ]),
        "inputs": '{"audio_features":{},"transcript":"...","target_accent":"en-US"}',
        "outputs": '{"accent_profile":"South Asian English","intelligibility":88,"drills":["th sound","r-coloring"]}',
        "tools": "Acoustic model, drill library",
        "models_table": fmt_models("Custom classifier", "GPT-4o-mini"),
        "memory": "PostgreSQL (accent progress)",
        "prompt": "Describe accent traits neutrally; focus on intelligibility not judgment.",
        "workflows": "Pronunciation Agent → Accent Agent → practice plan",
        "kpis": fmt_list(["Intelligibility inter-rater agreement > 0.75"]),
        "failure": "Insufficient audio → request longer sample",
        "observability": "Accent distribution analytics (aggregated)",
        "security": "Avoid stereotyping language in outputs",
        "tests": fmt_list(["Non-native patterns identified", "Encouraging tone in feedback"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "13-speech-quality-agent",
        "num": 13,
        "name": "Speech Quality Agent",
        "wave": 2,
        "priority": "P2",
        "langgraph": "Voice Preprocess Node",
        "primary_model": "Signal processing (no LLM)",
        "purpose": "Detect microphone quality, noise, echo, and other audio issues before analysis.",
        "responsibilities": fmt_list([
            "SNR and noise floor measurement",
            "Clipping and echo detection",
            "Mic quality grading",
            "User guidance for better recording",
        ]),
        "inputs": '{"audio_url":"s3://...","session_id":"uuid"}',
        "outputs": '{"quality":"fair","snr_db":18,"issues":["background_noise"],"guidance":"Move closer to mic"}',
        "tools": "FFmpeg, librosa, WebRTC VAD",
        "models_table": fmt_models("DSP rules", "N/A"),
        "memory": "Redis (last quality check per session)",
        "prompt": "N/A — rule-based agent",
        "workflows": "Audio upload → Speech Quality → Pronunciation (if pass)",
        "kpis": fmt_list(["False reject rate < 10%", "Check latency < 500ms"]),
        "failure": "Cannot analyze → allow pipeline with warning flag",
        "observability": "Quality issue rate by device type",
        "security": "Process audio in memory; no long-term storage for QC-only passes",
        "tests": fmt_list(["Noisy cafe flagged", "Clean studio audio passes"]),
        "implementation": "Not implemented.",
    },
    # Wave 3
    {
        "slug": "14-emotion-detection-agent",
        "num": 14,
        "name": "Emotion Detection Agent",
        "wave": 3,
        "priority": "P1",
        "langgraph": "Affective Node",
        "primary_model": "Multimodal classifier + GPT-4o-mini",
        "purpose": "Detect student emotional state from voice, conversation, and optional facial cues.",
        "responsibilities": fmt_list([
            "Classify happy, confused, frustrated, excited, bored",
            "Fuse voice prosody and text sentiment",
            "Optional webcam emotion (with consent)",
            "Emit confidence scores",
        ]),
        "inputs": '{"transcript":"...","audio_features":{},"facial_features":"optional","session_id":"uuid"}',
        "outputs": '{"emotion":"confused","confidence":0.87,"signals":["short replies","question marks"]}',
        "tools": "Sentiment model, prosody analyzer, optional vision API",
        "models_table": fmt_models("GPT-4o-mini", "text sentiment model"),
        "memory": "Redis (session affect timeline)",
        "prompt": "Infer dominant emotion from multimodal cues; avoid overconfidence.",
        "workflows": "Each turn → Emotion Detection → Orchestrator adapts tone",
        "kpis": fmt_list(["F1 > 0.7 on labeled emotions", "Latency < 800ms"]),
        "failure": "Low confidence → default neutral; do not change teaching style drastically",
        "observability": "Emotion distribution per session",
        "security": "Facial data requires explicit opt-in; delete after inference",
        "tests": fmt_list(["Frustrated language detected", "Neutral small talk → neutral"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "15-confidence-agent",
        "num": 15,
        "name": "Confidence Agent",
        "wave": 3,
        "priority": "P1",
        "langgraph": "Affective Node",
        "primary_model": "GPT-4o-mini",
        "purpose": "Measure student confidence, self-belief, and communication courage on a 0–100 scale.",
        "responsibilities": fmt_list([
            "Linguistic confidence markers",
            "Hesitation vs assertion patterns",
            "Longitudinal confidence tracking",
            "Actionable confidence boosts",
        ]),
        "inputs": '{"transcript":"...","history":[],"fluency_score":84}',
        "outputs": '{"confidence":67,"trend":"improving","factors":["fewer fillers"],"encouragement":"..."}',
        "tools": "Fluency Agent output, historical metrics",
        "models_table": fmt_models("GPT-4o-mini", "weighted rules"),
        "memory": "PostgreSQL (confidence time series)",
        "prompt": "Score confidence 0–100 with evidence; one specific praise and one gentle challenge.",
        "workflows": "Post-session → Confidence Agent → Progress Agent",
        "kpis": fmt_list(["Score correlates with teacher ratings r > 0.6"]),
        "failure": "Insufficient history → session-only estimate with wide band",
        "observability": "Confidence trend dashboards",
        "security": "Individual scores visible only to student and authorized teachers",
        "tests": fmt_list(["Hesitant speech → lower score", "Assertive answers → higher score"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "16-engagement-agent",
        "num": 16,
        "name": "Engagement Agent",
        "wave": 3,
        "priority": "P1",
        "langgraph": "Affective Node",
        "primary_model": "GPT-4o-mini",
        "purpose": "Detect attention, participation, and interest during learning sessions.",
        "responsibilities": fmt_list([
            "Response latency and length analysis",
            "Participation rate",
            "Topic interest signals",
            "Disengagement alerts",
        ]),
        "inputs": '{"session_id":"uuid","turns":[{"role":"student","text":"...","ts":0}],"duration_sec":600}',
        "outputs": '{"engagement":72,"attention":"medium","alerts":[],"suggestions":["ask opinion question"]}',
        "tools": "Session Manager, turn analytics",
        "models_table": fmt_models("GPT-4o-mini", "heuristics"),
        "memory": "Redis (live session), PostgreSQL (aggregates)",
        "prompt": "Identify engagement drops; suggest one re-engagement tactic.",
        "workflows": "Live session monitoring → Engagement Agent → Orchestrator",
        "kpis": fmt_list(["Disengagement detected within 2 turns", "Alert precision > 70%"]),
        "failure": "Sparse turns → mark engagement unknown",
        "observability": "Engagement heatmaps by lesson type",
        "security": "No biometric inference without consent",
        "tests": fmt_list(["Monosyllabic replies → low engagement", "Active Q&A → high engagement"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "17-stress-detection-agent",
        "num": 17,
        "name": "Stress Detection Agent",
        "wave": 3,
        "priority": "P2",
        "langgraph": "Affective Node",
        "primary_model": "GPT-4o-mini + prosody",
        "purpose": "Detect exam anxiety, fear, frustration, and burnout signals.",
        "responsibilities": fmt_list([
            "Stress level classification",
            "Trigger identification",
            "Escalation to human support when severe",
            "Calming intervention suggestions",
        ]),
        "inputs": '{"transcript":"...","audio_features":{},"context":{"upcoming_exam":true}}',
        "outputs": '{"stress_level":"moderate","type":"exam_anxiety","intervention":"breathing exercise","escalate":false}',
        "tools": "Prosody analyzer, crisis keyword list",
        "models_table": fmt_models("GPT-4o-mini", "keyword rules"),
        "memory": "PostgreSQL (stress events, encrypted)",
        "prompt": "Detect stress compassionately; never diagnose medical conditions.",
        "workflows": "Emotion Agent → Stress Detection → Motivation Agent",
        "kpis": fmt_list(["Severe stress recall > 90%", "False escalation < 2%"]),
        "failure": "Crisis keywords → immediate safe response template + human alert",
        "observability": "Anonymized stress trend reports",
        "security": "Crisis protocol; regional helpline numbers in responses",
        "tests": fmt_list(["Exam panic language triggers moderate stress", "Crisis language escalates"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "18-motivation-agent",
        "num": 18,
        "name": "Motivation Agent",
        "wave": 3,
        "priority": "P1",
        "langgraph": "Affective Node",
        "primary_model": "GPT-4o",
        "purpose": "Deliver encouragement, goal reinforcement, and positive feedback adapted to student state.",
        "responsibilities": fmt_list([
            "Personalized praise",
            "Goal reminder linkage",
            "Streak and milestone celebration",
            "Re-engagement messaging",
        ]),
        "inputs": '{"student_id":"uuid","emotion":"frustrated","goals":[],"recent_wins":[]}',
        "outputs": '{"message":"You improved fluency 12% this week!","tone":"warm","cta":"Try one more minute"}',
        "tools": "Goal Tracker, Progress Agent, Memory Agent",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (motivation history)",
        "prompt": "Be genuine and specific; tie encouragement to real progress data.",
        "workflows": "Negative affect detected → Motivation Agent → Conversation Agent",
        "kpis": fmt_list(["Student satisfaction +10% when active", "Repeat session rate uplift"]),
        "failure": "No progress data → generic but honest encouragement",
        "observability": "Motivation message acceptance rate",
        "security": "Avoid manipulative dark patterns",
        "tests": fmt_list(["Frustrated student gets empathy first", "Milestone triggers celebration"]),
        "implementation": "Not implemented.",
    },
    # Wave 4
    {
        "slug": "19-assessment-agent",
        "num": 19,
        "name": "Assessment Agent",
        "wave": 4,
        "priority": "P0",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Evaluate student understanding, retention, application, and analysis ability.",
        "responsibilities": fmt_list([
            "Formative and summative assessment",
            "Rubric-based scoring",
            "Skill breakdown by domain",
            "Store results for Progress Agent",
        ]),
        "inputs": '{"student_id":"uuid","responses":[],"rubric":"CEFR","topic":"present perfect"}',
        "outputs": '{"overall_score":78,"skills":{"grammar":80,"vocabulary":75},"gaps":["irregular verbs"]}',
        "tools": "Rubric engine, Memory Agent",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (assessment results)",
        "prompt": "Score against rubric with evidence quotes from student answers.",
        "workflows": "Quiz complete → Assessment Agent → Weak Topic Agent",
        "kpis": fmt_list(["Inter-rater agreement with teachers > 0.8", "Assessment latency < 3s"]),
        "failure": "Incomplete answers → partial credit with explanation",
        "observability": "Score distribution by topic",
        "security": "Assessment data tenant-isolated",
        "tests": fmt_list(["Strong answer scores > 85", "Empty answer scores 0 with feedback"]),
        "implementation": "Partial: `assessment` agent stub exists; frontend assessment page present.",
    },
    {
        "slug": "20-bloom-taxonomy-agent",
        "num": 20,
        "name": "Bloom Taxonomy Agent",
        "wave": 4,
        "priority": "P2",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Measure cognitive levels: Remember, Understand, Apply, Analyze, Evaluate, Create.",
        "responsibilities": fmt_list([
            "Classify question and answer cognitive level",
            "Balance lesson across Bloom levels",
            "Recommend higher-order tasks",
            "Track cognitive growth",
        ]),
        "inputs": '{"questions":[],"answers":[],"lesson_id":"uuid"}',
        "outputs": '{"levels":{"remember":2,"understand":3,"apply":1},"dominant":"understand","recommendation":"add apply task"}',
        "tools": "Bloom classifier, curriculum metadata",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (Bloom history)",
        "prompt": "Map each interaction to Bloom level with brief justification.",
        "workflows": "Assessment Agent → Bloom Agent → Curriculum Agent",
        "kpis": fmt_list(["Classification accuracy > 85% on gold set"]),
        "failure": "Ambiguous task → mark as understand default",
        "observability": "Bloom mix per course",
        "security": "N/A",
        "tests": fmt_list(["Recall question → remember", "Essay critique → evaluate"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "21-weak-topic-agent",
        "num": 21,
        "name": "Weak Topic Agent",
        "wave": 4,
        "priority": "P1",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o-mini",
        "purpose": "Identify knowledge gaps, skill gaps, and misconceptions from assessment and conversation data.",
        "responsibilities": fmt_list([
            "Aggregate errors across agents",
            "Rank weak topics by impact",
            "Detect persistent misconceptions",
            "Feed Recommendation and Curriculum agents",
        ]),
        "inputs": '{"student_id":"uuid","assessments":[],"grammar_errors":[],"memory_snapshot":{}}',
        "outputs": '{"weak_topics":[{"topic":"articles","severity":0.8,"evidence_count":12}],"misconceptions":["a vs an rule"]}',
        "tools": "Memory Agent, Assessment Agent, analytics SQL",
        "models_table": fmt_models("GPT-4o-mini", "SQL aggregates"),
        "memory": "PostgreSQL + Memory Agent",
        "prompt": "Prioritize top 3 weak areas with evidence counts.",
        "workflows": "Post-assessment → Weak Topic → Recommendation Agent",
        "kpis": fmt_list(["Top-3 weak topics match teacher review > 75%"]),
        "failure": "Sparse data → return exploratory topics from level defaults",
        "observability": "Weak topic heatmap per cohort",
        "security": "Student-level data access controls",
        "tests": fmt_list(["Repeated article errors surface articles", "New student gets level defaults"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "22-quiz-agent",
        "num": 22,
        "name": "Quiz Agent",
        "wave": 4,
        "priority": "P1",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Generate MCQs, adaptive questions, and case studies tailored to student level.",
        "responsibilities": fmt_list([
            "MCQ and open-ended generation",
            "Adaptive difficulty",
            "Distractor quality",
            "Anti-repeat from recent quizzes",
        ]),
        "inputs": '{"topic":"conditionals","level":"B1","count":5,"weak_topics":["type 2"]}',
        "outputs": '{"questions":[{"type":"mcq","stem":"...","options":[],"answer":1,"bloom":"apply"}]}',
        "tools": "RAG Agent, question bank, randomization",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (question history)",
        "prompt": "Generate valid MCQs with one clear answer and plausible distractors.",
        "workflows": "Weak Topic Agent → Quiz Agent → student UI",
        "kpis": fmt_list(["Teacher approval rate > 90%", "Duplicate rate < 5%"]),
        "failure": "Invalid JSON → regenerate once; still fail → use bank fallback",
        "observability": "Question difficulty calibration",
        "security": "No leaked answers in prompts/logs",
        "tests": fmt_list(["5 questions returned", "Difficulty adapts after correct streak"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "23-homework-agent",
        "num": 23,
        "name": "Homework Agent",
        "wave": 4,
        "priority": "P1",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Generate assignments, projects, and exercises aligned to lesson outcomes.",
        "responsibilities": fmt_list([
            "Exercise generation by skill",
            "Estimated completion time",
            "Differentiation by level",
            "Submission rubric",
        ]),
        "inputs": '{"lesson_id":"uuid","student_id":"uuid","weak_topics":[],"duration_min":30}',
        "outputs": '{"homework":{"title":"...","tasks":[],"rubric":{},"due_in_days":3}}',
        "tools": "RAG Agent, Curriculum Agent",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (homework assignments)",
        "prompt": "Create achievable homework linked to today's lesson and weak areas.",
        "workflows": "Lesson end → Homework Agent → notify student",
        "kpis": fmt_list(["Completion rate > 60%", "Teacher edit rate < 20%"]),
        "failure": "Content policy block → simplify task",
        "observability": "Homework completion funnel",
        "security": "Age-appropriate content checks via Moderation Agent",
        "tests": fmt_list(["Homework references lesson topic", "Rubric included"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "24-recommendation-agent",
        "num": 24,
        "name": "Recommendation Agent",
        "wave": 4,
        "priority": "P1",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Generate daily and weekly learning plans and course suggestions.",
        "responsibilities": fmt_list([
            "Daily micro-plans",
            "Weekly study schedules",
            "Course and resource recommendations",
            "Balance skills across week",
        ]),
        "inputs": '{"student_id":"uuid","goals":[],"weak_topics":[],"available_min_per_day":20}',
        "outputs": '{"daily_plan":[{"day":"Mon","tasks":[]}],"courses":["IELTS Prep B1"]}',
        "tools": "Weak Topic Agent, Goal Tracker, RAG Agent",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (plans)",
        "prompt": "Build realistic plans respecting time budget and goals.",
        "workflows": "Weekly cron → Recommendation Agent → student dashboard",
        "kpis": fmt_list(["Plan adherence > 50%", "Goal progress correlation"]),
        "failure": "Missing goals → default skill-balanced plan",
        "observability": "Recommendation click-through rate",
        "security": "N/A",
        "tests": fmt_list(["20 min/day respected", "Weak topic appears in plan"]),
        "implementation": "Partial: `planner` agent stub in AGENT_REGISTRY.",
    },
    {
        "slug": "25-curriculum-agent",
        "num": 25,
        "name": "Curriculum Agent",
        "wave": 4,
        "priority": "P2",
        "langgraph": "Learning Node",
        "primary_model": "GPT-4o",
        "purpose": "Create lesson sequences, topic progression, and skill maps.",
        "responsibilities": fmt_list([
            "Scope and sequence design",
            "Prerequisite mapping",
            "Skill map visualization data",
            "Align to standards (CEFR, IELTS)",
        ]),
        "inputs": '{"course_goal":"B2 conversation","weeks":12,"hours_per_week":3}',
        "outputs": '{"sequence":[{"week":1,"topics":[],"skills":[]}],"skill_map":{}}',
        "tools": "RAG Agent, standards library",
        "models_table": fmt_models("GPT-4o", "template library"),
        "memory": "PostgreSQL (curriculum versions)",
        "prompt": "Design pedagogically sound progression with spaced review.",
        "workflows": "Institution onboarding → Curriculum Agent → course publish",
        "kpis": fmt_list(["Teacher approval > 85%", "Learning outcome lift vs unstructured"]),
        "failure": "Overlong plan → compress with teacher review flag",
        "observability": "Curriculum version diff audit",
        "security": "Institution-owned IP protected",
        "tests": fmt_list(["Prerequisites ordered correctly", "CEFR alignment tagged"]),
        "implementation": "Not implemented.",
    },
    # Wave 5
    {
        "slug": "26-student-profile-agent",
        "num": 26,
        "name": "Student Profile Agent",
        "wave": 5,
        "priority": "P1",
        "langgraph": "Profile Node",
        "primary_model": "GPT-4o-mini + SQL",
        "purpose": "Maintain holistic learning profile, growth metrics, and behavior data.",
        "responsibilities": fmt_list([
            "Unified learner profile",
            "Growth metrics aggregation",
            "Behavioral pattern summary",
            "Profile API for other agents",
        ]),
        "inputs": '{"student_id":"uuid","refresh":"full|incremental"}',
        "outputs": '{"profile":{"level":"B1","strengths":[],"behaviors":{"sessions_per_week":4}}}',
        "tools": "PostgreSQL, Memory Agent, analytics",
        "models_table": fmt_models("GPT-4o-mini", "SQL only"),
        "memory": "PostgreSQL (profiles)",
        "prompt": "Summarize learner in 3 bullets for teacher dashboard.",
        "workflows": "Nightly job → Student Profile → Dashboard Agent",
        "kpis": fmt_list(["Profile freshness < 24h", "Dashboard load < 2s"]),
        "failure": "Partial data → mark fields stale",
        "observability": "Profile completeness score",
        "security": "FERPA/GDPR field-level access",
        "tests": fmt_list(["Profile merges assessment + conversation data", "PII fields masked for teachers without consent"]),
        "implementation": "Not implemented. User table exists in DB.",
    },
    {
        "slug": "27-goal-tracker-agent",
        "num": 27,
        "name": "Goal Tracker Agent",
        "wave": 5,
        "priority": "P1",
        "langgraph": "Profile Node",
        "primary_model": "Rules + GPT-4o-mini",
        "purpose": "Track English fluency, IELTS, exam prep, and communication goals.",
        "responsibilities": fmt_list([
            "Goal CRUD and milestones",
            "Progress percent calculation",
            "Deadline reminders",
            "Goal attainment prediction",
        ]),
        "inputs": '{"student_id":"uuid","goal":{"type":"IELTS","target_band":7,"deadline":"2026-12-01"}}',
        "outputs": '{"progress_pct":42,"on_track":true,"milestones":[{"name":"Band 6.5 mock","done":false}]}',
        "tools": "Progress Agent, Assessment Agent",
        "models_table": fmt_models("GPT-4o-mini", "linear projection"),
        "memory": "PostgreSQL (goals)",
        "prompt": "Explain goal progress in plain language with next milestone.",
        "workflows": "Student sets goal → Goal Tracker → Motivation Agent",
        "kpis": fmt_list(["Goal completion rate > 40%", "Reminder open rate > 25%"]),
        "failure": "Unrealistic goal → suggest adjusted target",
        "observability": "Goal type distribution",
        "security": "Goals visible to student and linked parent account",
        "tests": fmt_list(["IELTS goal tracks band progress", "Past deadline flags off-track"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "28-progress-agent",
        "num": 28,
        "name": "Progress Agent",
        "wave": 5,
        "priority": "P1",
        "langgraph": "Profile Node",
        "primary_model": "SQL + GPT-4o-mini",
        "purpose": "Create weekly, monthly, and yearly progress reports.",
        "responsibilities": fmt_list([
            "Time-bucketed metrics",
            "Skill trend charts data",
            "Comparison to personal baseline",
            "Export for Parent Report Agent",
        ]),
        "inputs": '{"student_id":"uuid","period":"week|month|year","end_date":"2026-07-26"}',
        "outputs": '{"period":"week","metrics":{"fluency_delta":5,"sessions":4},"narrative":"..."}',
        "tools": "PostgreSQL analytics, chart data API",
        "models_table": fmt_models("GPT-4o-mini", "template narrative"),
        "memory": "PostgreSQL (progress snapshots)",
        "prompt": "Write concise progress narrative highlighting wins and one focus area.",
        "workflows": "Scheduled job → Progress Agent → Parent Report / Dashboard",
        "kpis": fmt_list(["Report generation < 5s", "Narrative accuracy per teacher review"]),
        "failure": "No activity in period → encouragement + suggested restart plan",
        "observability": "Report generation success rate",
        "security": "Reports respect parent visibility settings",
        "tests": fmt_list(["Week report includes session count", "Year report aggregates monthly"]),
        "implementation": "Partial: `progress` agent stub in AGENT_REGISTRY.",
    },
    {
        "slug": "29-parent-report-agent",
        "num": 29,
        "name": "Parent Report Agent",
        "wave": 5,
        "priority": "P2",
        "langgraph": "Report Node",
        "primary_model": "GPT-4o",
        "purpose": "Generate parent-friendly reports, recommendations, and improvement plans.",
        "responsibilities": fmt_list([
            "Non-technical language summaries",
            "Strengths and areas to support at home",
            "Actionable parent tips",
            "PDF/email delivery",
        ]),
        "inputs": '{"student_id":"uuid","period":"month","parent_locale":"en"}',
        "outputs": '{"report_html":"...","recommendations":["Practice 10 min daily"],"improvement_plan":{}}',
        "tools": "Progress Agent, Goal Tracker, email service",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "PostgreSQL (sent reports archive)",
        "prompt": "Write for parents: clear, positive, no jargon; include one home activity.",
        "workflows": "Monthly cron → Parent Report → email",
        "kpis": fmt_list(["Parent satisfaction > 4/5", "Open rate > 50%"]),
        "failure": "Missing parent email → queue for in-app notification",
        "observability": "Delivery and open tracking",
        "security": "COPPA parent consent required; no peer comparisons by default",
        "tests": fmt_list(["Report excludes internal agent names", "Includes weekly study time"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "30-teacher-dashboard-agent",
        "num": 30,
        "name": "Teacher Dashboard Agent",
        "wave": 5,
        "priority": "P1",
        "langgraph": "Report Node",
        "primary_model": "GPT-4o-mini + SQL",
        "purpose": "Support teacher insights, class analytics, and performance analytics.",
        "responsibilities": fmt_list([
            "Class-level aggregates",
            "At-risk student flags",
            "Lesson effectiveness signals",
            "Natural language class summary",
        ]),
        "inputs": '{"teacher_id":"uuid","class_id":"uuid","date_range":{"from":"...","to":"..."}}',
        "outputs": '{"summary":"...","at_risk":[{"student_id":"...","reason":"low engagement"}],"charts":{}}',
        "tools": "Analytics Agent, Student Profile Agent",
        "models_table": fmt_models("GPT-4o-mini", "SQL aggregates"),
        "memory": "PostgreSQL (cached dashboards)",
        "prompt": "Highlight 3 class insights and 3 students needing attention.",
        "workflows": "Teacher opens dashboard → Teacher Dashboard Agent",
        "kpis": fmt_list(["Dashboard P95 < 3s", "At-risk precision > 70%"]),
        "failure": "Large class → paginate and pre-aggregate",
        "observability": "Dashboard query performance",
        "security": "Teacher sees only assigned classes",
        "tests": fmt_list(["Class of 30 loads under 3s", "At-risk flag on zero sessions"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "31-analytics-agent",
        "num": 31,
        "name": "Analytics Agent",
        "wave": 5,
        "priority": "P1",
        "langgraph": "Analytics Node",
        "primary_model": "Python analytics service",
        "purpose": "Produce learning, behavioral, and trend analytics for institution dashboards.",
        "responsibilities": fmt_list([
            "Learning outcome trends",
            "Behavioral cohort analysis",
            "Funnel and retention metrics",
            "Export to BI tools",
        ]),
        "inputs": '{"tenant_id":"uuid","metric":"retention","granularity":"week","filters":{}}',
        "outputs": '{"series":[],"insights":["Retention up 8% MoM"],"anomalies":[]}',
        "tools": "PostgreSQL, ClickHouse (optional), Python pandas",
        "models_table": fmt_models("Python service", "SQL"),
        "memory": "Warehouse tables",
        "prompt": "N/A — primarily deterministic analytics",
        "workflows": "ETL → Analytics Agent → institution admin UI",
        "kpis": fmt_list(["Query SLA < 10s for standard reports", "Data freshness < 1h"]),
        "failure": "Heavy query → async job + email when ready",
        "observability": "Query cost and cache hit rate",
        "security": "Tenant isolation; k-anonymity for small cohorts",
        "tests": fmt_list(["Retention cohort correct", "Small cohort suppressed"]),
        "implementation": "Not implemented.",
    },
    # Wave 6
    {
        "slug": "32-moderation-agent",
        "num": 32,
        "name": "Moderation Agent",
        "wave": 6,
        "priority": "P0",
        "langgraph": "Safety Gate Node",
        "primary_model": "Moderation API + GPT-4o-mini",
        "purpose": "Detect unsafe content, abuse, and age-sensitive material in inputs and outputs.",
        "responsibilities": fmt_list([
            "Input and output moderation",
            "Abuse and harassment detection",
            "Age-appropriate filtering",
            "Block or sanitize with audit log",
        ]),
        "inputs": '{"text":"...","direction":"input|output","user_age":14}',
        "outputs": '{"safe":false,"categories":["harassment"],"action":"block","sanitized":null}',
        "tools": "OpenAI Moderation, custom blocklists",
        "models_table": fmt_models("omni-moderation-latest", "keyword list"),
        "memory": "PostgreSQL (moderation events)",
        "prompt": "Classify safety risk; prefer block over false negative for minors.",
        "workflows": "All messages → Moderation Gate → Orchestrator",
        "kpis": fmt_list(["Recall on unsafe content > 95%", "False positive < 3%"]),
        "failure": "API down → conservative keyword block + alert",
        "observability": "Moderation rate and category breakdown",
        "security": "First line of defense; integrates with Policy Agent",
        "tests": fmt_list(["Profanity blocked for minors", "Educational violence context allowed"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "33-hallucination-checker-agent",
        "num": 33,
        "name": "Hallucination Checker Agent",
        "wave": 6,
        "priority": "P1",
        "langgraph": "Safety Gate Node",
        "primary_model": "GPT-4o + RAG verification",
        "purpose": "Verify facts, educational responses, and generated content against trusted sources.",
        "responsibilities": fmt_list([
            "Claim extraction",
            "RAG cross-check",
            "Confidence scoring",
            "Flag or rewrite unsupported claims",
        ]),
        "inputs": '{"response":"...","sources":[],"subject":"grammar"}',
        "outputs": '{"verified":false,"claims":[{"text":"...","supported":false}],"suggested_fix":"..."}',
        "tools": "RAG Agent, fact DB",
        "models_table": fmt_models("GPT-4o", "GPT-4o-mini"),
        "memory": "Qdrant (verified facts cache)",
        "prompt": "List factual claims; mark supported only with source evidence.",
        "workflows": "Teacher Agent output → Hallucination Checker → user",
        "kpis": fmt_list(["Hallucination rate < 2% on eval set", "Latency < 2s"]),
        "failure": "No sources → add uncertainty disclaimer",
        "observability": "Unsupported claim rate by subject",
        "security": "Do not leak source content across tenants",
        "tests": fmt_list(["False historical fact flagged", "Common grammar rule passes"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "34-citation-agent",
        "num": 34,
        "name": "Citation Agent",
        "wave": 6,
        "priority": "P2",
        "langgraph": "Safety Gate Node",
        "primary_model": "GPT-4o-mini",
        "purpose": "Add references, sources, and attributions to teaching content.",
        "responsibilities": fmt_list([
            "Map claims to RAG sources",
            "Format citations (APA simple)",
            "Inline reference links",
            "Bibliography generation",
        ]),
        "inputs": '{"response":"...","rag_chunks":[{"source":"Lesson 2","id":"..."}]}',
        "outputs": '{"cited_response":"... [1]","references":[{"id":1,"title":"Lesson 2"}]}',
        "tools": "RAG Agent metadata",
        "models_table": fmt_models("GPT-4o-mini", "template"),
        "memory": "N/A",
        "prompt": "Insert minimal inline citations without disrupting readability.",
        "workflows": "RAG + Teacher → Citation Agent → student",
        "kpis": fmt_list(["Citation accuracy > 95%", "Added latency < 500ms"]),
        "failure": "No chunks → skip citations",
        "observability": "Citation coverage rate",
        "security": "Only cite tenant-approved sources",
        "tests": fmt_list(["Two sources → two references", "No sources → unchanged text"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "35-privacy-agent",
        "num": 35,
        "name": "Privacy Agent",
        "wave": 6,
        "priority": "P0",
        "langgraph": "Safety Gate Node",
        "primary_model": "NER + regex + GPT-4o-mini",
        "purpose": "Detect PII and sensitive information in logs, prompts, and exports.",
        "responsibilities": fmt_list([
            "PII detection and redaction",
            "Sensitive data classification",
            "Log scrubbing",
            "DSAR delete orchestration",
        ]),
        "inputs": '{"text":"...","context":"log|prompt|export","student_id":"uuid"}',
        "outputs": '{"redacted_text":"...","pii_found":["email"],"action":"redact"}',
        "tools": "Presidio or similar NER, regex patterns",
        "models_table": fmt_models("NER model", "regex"),
        "memory": "Audit log only (redacted)",
        "prompt": "Identify PII types; never echo raw PII in output.",
        "workflows": "Pre-log → Privacy Agent → observability backend",
        "kpis": fmt_list(["PII recall > 98%", "False redaction < 1%"]),
        "failure": "Uncertain → redact aggressively",
        "observability": "PII detection counts (no raw values)",
        "security": "Core compliance component; pairs with Compliance Agent",
        "tests": fmt_list(["Email redacted in logs", "Name in lesson example preserved if fictional"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "36-policy-agent",
        "num": 36,
        "name": "Policy Agent",
        "wave": 6,
        "priority": "P1",
        "langgraph": "Safety Gate Node",
        "primary_model": "Rules engine + GPT-4o-mini",
        "purpose": "Enforce school policies, learning policies, and safety rules per tenant.",
        "responsibilities": fmt_list([
            "Tenant policy rule evaluation",
            "Blocked topics and hours",
            "Allowed model/tool restrictions",
            "Policy violation responses",
        ]),
        "inputs": '{"tenant_id":"uuid","action":"teach","topic":"...","user_role":"student"}',
        "outputs": '{"allowed":true,"violations":[],"message":null}',
        "tools": "Policy store (PostgreSQL), Admin API",
        "models_table": fmt_models("Rules engine", "GPT-4o-mini"),
        "memory": "PostgreSQL (policy versions)",
        "prompt": "Explain policy violation neutrally with allowed alternative.",
        "workflows": "Orchestrator → Policy Agent → proceed or block",
        "kpis": fmt_list(["Zero unauthorized policy bypass", "Evaluation < 50ms"]),
        "failure": "Policy store down → deny by default for K-12 tenants",
        "observability": "Violation counts by rule ID",
        "security": "Immutable policy audit trail",
        "tests": fmt_list(["Blocked topic rejected", "After-hours rule for minor"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "37-compliance-agent",
        "num": 37,
        "name": "Compliance Agent",
        "wave": 6,
        "priority": "P1",
        "langgraph": "Governance Node",
        "primary_model": "Rules + documentation",
        "purpose": "Support GDPR, FERPA, COPPA, SOC2, and ISO27001 compliance workflows.",
        "responsibilities": fmt_list([
            "Consent tracking",
            "Data retention enforcement",
            "Compliance report generation",
            "Cross-agent compliance checks",
        ]),
        "inputs": '{"request_type":"dsar_export|delete|audit","subject_id":"uuid","regulation":"GDPR"}',
        "outputs": '{"status":"completed","artifacts":["export.zip"],"audit_id":"..."}',
        "tools": "Privacy Agent, PostgreSQL, object storage",
        "models_table": fmt_models("Rules engine", "N/A"),
        "memory": "Compliance audit store",
        "prompt": "N/A — procedural agent",
        "workflows": "Admin request → Compliance Agent → coordinate deletes/exports",
        "kpis": fmt_list(["DSAR SLA < 30 days", "100% delete propagation"]),
        "failure": "Partial delete → rollback and alert DPO",
        "observability": "Compliance request queue depth",
        "security": "Highest privilege; MFA required",
        "tests": fmt_list(["GDPR export includes all student tables", "Delete removes Qdrant vectors"]),
        "implementation": "Not implemented.",
    },
    {
        "slug": "38-cost-optimization-agent",
        "num": 38,
        "name": "Cost Optimization Agent",
        "wave": 6,
        "priority": "P1",
        "langgraph": "Governance Node",
        "primary_model": "Routing rules + usage analytics",
        "purpose": "Dynamically route requests to the cheapest capable model per task type.",
        "responsibilities": fmt_list([
            "Model routing by intent and complexity",
            "Token budget enforcement",
            "Cost attribution per tenant/session",
            "A/B cost vs quality tradeoffs",
        ]),
        "inputs": '{"intent":"greeting","complexity":"low","tenant_budget_remaining":10.0}',
        "outputs": '{"model":"gpt-4o-mini","reason":"simple greeting","estimated_cost":0.0001}',
        "tools": "Usage DB, model price table, Orchestrator hook",
        "models_table": fmt_models("Routing rules", "GPT-4o-mini default"),
        "memory": "PostgreSQL (usage and budgets)",
        "prompt": "N/A — routing agent",
        "workflows": "Orchestrator → Cost Optimization → LLM provider",
        "kpis": fmt_list(["30–60% LLM cost reduction", "Quality regression < 5% on eval"]),
        "failure": "Budget exceeded → downgrade or queue",
        "observability": "Cost per agent, per tenant dashboards",
        "security": "Prevent cost-based denial of service across tenants",
        "tests": fmt_list(["Greeting → mini model", "Complex essay → full model"]),
        "implementation": "Not implemented. Current: single model per AI_PROVIDER in config.",
    },
]


def main() -> None:
    for agent in AGENTS:
        write(**agent)
    print("done")


if __name__ == "__main__":
    main()
